spring:
  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: alpha.capitalis1@gmail.com
    password: AlphaCapitalis1!
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  #Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://207.180.242.236:5432/alphacloud
    username: acadmin
    password: ac-admin!12345
  # JPA properties
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
  # Flyway
  flyway:
    enabled: true
    locations:
      - classpath:/db/migration
#JWT
jwt:
  secret: financeAlphaCloud!(562367213517?ALPHA
  expirationInMinutes: 150
  issuer: Alpha-cloud
#  allowedOrigin: 'http://173.212.198.199:8090'
